# Generated by Django 5.2 on 2025-04-05 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R1', models.IntegerField()),
                ('R2', models.IntegerField()),
                ('R3', models.IntegerField()),
                ('R4', models.IntegerField()),
                ('R5', models.IntegerField()),
                ('R_comments', models.TextField(blank=True, null=True)),
                ('L1', models.IntegerField()),
                ('L2', models.IntegerField()),
                ('L3', models.IntegerField()),
                ('L4', models.IntegerField()),
                ('L5', models.IntegerField()),
                ('L_comments', models.TextField(blank=True, null=True)),
                ('H1', models.IntegerField()),
                ('H2', models.IntegerField()),
                ('H3', models.IntegerField()),
                ('H4', models.IntegerField()),
                ('H5', models.IntegerField()),
                ('H_comments', models.TextField(blank=True, null=True)),
                ('E1', models.IntegerField()),
                ('E2', models.IntegerField()),
                ('E3', models.IntegerField()),
                ('E4', models.IntegerField()),
                ('E_comments', models.TextField(blank=True, null=True)),
                ('C1', models.IntegerField()),
                ('C2', models.IntegerField()),
                ('C3', models.IntegerField()),
                ('C4', models.IntegerField()),
                ('C5', models.IntegerField()),
                ('C6', models.IntegerField()),
                ('C_comments', models.TextField(blank=True, null=True)),
                ('M1', models.IntegerField()),
                ('M2', models.IntegerField()),
                ('M_comments', models.TextField(blank=True, null=True)),
                ('V1', models.IntegerField()),
                ('V2', models.IntegerField()),
                ('V3', models.IntegerField()),
                ('V4', models.IntegerField()),
                ('V5', models.IntegerField()),
                ('V_comments', models.TextField(blank=True, null=True)),
                ('final_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_code', models.CharField(max_length=20)),
                ('position_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R', models.FloatField()),
                ('L', models.FloatField()),
                ('H', models.FloatField()),
                ('E', models.FloatField()),
                ('C', models.FloatField()),
                ('M', models.FloatField()),
                ('V', models.FloatField()),
                ('final_score', models.FloatField()),
                ('performance_level', models.CharField(max_length=50)),
                ('evaluation_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='System.position')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_type', models.CharField(max_length=50)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='System.position')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='System.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_ts', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Temp_EvaluationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_cycle', models.CharField(max_length=50)),
                ('evaluation_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='System.evaluationdetails')),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='System.summary')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_employee_assignments', to='System.usuario')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_evaluator_assignments', to='System.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='summary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_summaries', to='System.usuario'),
        ),
        migrations.AddField(
            model_name='summary',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_summaries', to='System.usuario'),
        ),
        migrations.CreateModel(
            name='Permanent_EvaluationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_cycle', models.CharField(max_length=50)),
                ('evaluation_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='System.evaluationdetails')),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='System.summary')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_employee_assignments', to='System.usuario')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_evaluator_assignments', to='System.usuario')),
            ],
        ),
    ]
