# Generated by Django 5.2 on 2025-04-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetscore',
            name='created_at',
        ),
    ]
