# Generated by Django 5.2 on 2025-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_evaluationcycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationdetails',
            name='L1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationdetails',
            name='L2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationdetails',
            name='L3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationdetails',
            name='L4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationdetails',
            name='L5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='L',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
